services:
  web:
    container_name: web
    user: ${MY_UID}:${MY_GID}
    build:
      context: ./docker
      dockerfile: Dockerfile.php
      args:
        UID: ${MY_UID}
        GID: ${MY_GID}
    ports:
      - 8080:80
    volumes:
      - "./php:/var/www/html"

  mariadb:
    container_name: mariadb
    user: ${MY_UID}:${MY_GID}
    build:
      context: ./docker
      dockerfile: Dockerfile.mariadb
      args:
        UID: ${MY_UID}
        GID: ${MY_GID}
    environment:
      - MARIADB_ROOT_PASSWORD=password_root
      - MARIADB_DATABASE=nome_database
    ports:
      - 3306:3306
    volumes:
      - "./mariadb:/var/lib/mysql"
      - "./docker/init.sql:/docker-entrypoint-initdb.d/init.sql"

  react:
    container_name: react
    user: ${MY_UID}:${MY_GID}
    build:
      context: ./docker
      dockerfile: Dockerfile.react
      args:
        UID: ${MY_UID}
        GID: ${MY_GID}
    ports:
      - 3000:3000
    volumes:
      - "./app:/app"
